const product = [
  {
    id: 1,
    name: "HAVIT HV-G92 Gamepad",
    img: "http://localhost:3000/assets/AllPoduct/HAVIT HV-G92 Gamepad.png",
    mainPrice: 120,
    discountPrice: 160,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    ratting: 96,
    category: "gaming",
  },
  {
    id: 2,
    name: "AK-900 Wired Keyboard",
    img: "http://localhost:3000/assets/AllPoduct/AK-900 Wired Keyboard.png",
    mainPrice: 160,
    discountPrice: 250,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    ratting: 69,
    category: "computers",
  },
  {
    id: 3,
    name: "Seanner",
    img: "http://localhost:3000/assets/AllPoduct/IPS LCD Gaming Monitor.png",
    mainPrice: 1000,
    discountPrice: 16000,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    ratting: 99,
    category: "computers",
  },
  {
    id: 4,
    name: "Biometric Fingerprint Scanner",
    img: "http://localhost:3000/assets/AllPoduct/Biometric Fingerprint Scanner.png",
    mainPrice: 120,
    discountPrice: 160,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    ratting: 78,
    category: "scanner",
  },
  {
    id: 5,
    name: "ASUS FHD Gaming Laptop",
    img: "http://localhost:3000/assets/AllPoduct/ASUS FHD Gaming Laptop.png",
    mainPrice: 1500,
    discountPrice: 2000,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    ratting: 87,
    category: "laptop",
  },
  {
    id: 6,
    name: "GP11 Shooter USB Gamepad",
    img: "http://localhost:3000/assets/AllPoduct/GP11 Shooter USB Gamepad.png",
    mainPrice: 508,
    discountPrice: 978,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    ratting: 59,
    category: "gaming",
  },
  {
    id: 7,
    name: "Kids Electric Car",
    img: "http://localhost:3000/assets/AllPoduct/Kids Electric Car.png",
    mainPrice: 120,
    discountPrice: 160,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    ratting: 96,
    category: "Car",
  },
  {
    id: 8,
    name: "PlayStation 5",
    img: "http://localhost:3000/assets/AllPoduct/PlayStation 5.png",
    mainPrice: 130,
    discountPrice: 190,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    ratting: 87,
    category: "gaming",
  },
  {
    id: 9,
    name: "Speakers",
    img: "http://localhost:3000/assets/AllPoduct/Speakers.png",
    mainPrice: 1870,
    discountPrice: 1200,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    ratting: 73,
    category: "Speakers",
  },
  {
    id: 10,
    name: "Women’s Collections",
    img: "http://localhost:3000/assets/AllPoduct/Women’s Collections.png",
    mainPrice: 100,
    discountPrice: 160,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    ratting: 82,
    category: "women",
  },
  {
    id: 11,
    name: "Printer",
    img: "http://localhost:3000/assets/AllPoduct/Printer.png",
    mainPrice: 100,
    discountPrice: 160,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    ratting: 81,
    category: "Printer",
  },
  {
    id: 12,
    name: "MARK Technologies",
    img: "http://localhost:3000/assets/AllPoduct/MARK Technologies.png",
    mainPrice: 100,
    discountPrice: 160,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    ratting: 87,
    category: "Technologies",
  },
];

export default product;
